# ui/constants.py

THEMES = {
    "Стандартная": {
        "bg": "#2b2b2b", "fg": "#d0ffd0",
        "menu_bg": "#2b2b2b", "menu_fg": "#00cc66", "menu_active_bg": "#4a4d50",
        "menu_active_fg": "#00ff88", "menu_highlight": "#008844",
        "left_header_bg": "#2b2b2b", "left_header_fg": "#aaffaa",
        "tree_bg": "#1e1e1e", "tree_fg": "#c0ffc0", "tree_sel_bg": "#2d4a3a",
        "tree_heading_bg": "#2b2b2b", "tree_heading_fg": "#66ff66",
        "tree_frame_highlight": "#008844",
        "btn_default_bg": "#4a4d50", "btn_default_fg": "#aaffaa",
        "btn_danger_bg": "#8a3a3a", "btn_danger_fg": "#ff8888",
        "btn_accent_bg": "#4a6d4a", "btn_accent_fg": "#66ff66",
        "hotbar_bg": "#1a1a1a", "hotbar_fg": "#00ff88", "hotbar_highlight": "#008844",
        "hotbar_btn_bg": "#2b2b2b", "hotbar_btn_fg": "#00cc66",
        "console_bg": "#000000", "console_fg": "#4af626", "console_highlight": "#008844",
        "scrollbar_bg": "#1a1a1a", "scrollbar_trough": "#101010",
        "scrollbar_arrow": "#00cc66", "scrollbar_active_bg": "#008844",
        "progress_trough": "#333333", "progress_light": "#00cc66", "progress_dark": "#00994d",
        "select_bg": "#2d4a3a", "select_fg": "#ffffff",
        "scrollbar_thumb": "#008844", "scrollbar_thumb_active": "#00cc66",
        "scrollbar_thumb_hover": "#00aa55", "scrollbar_trough": "#101010",
        "scrollbar_border": "#006633", "scrollbar_arrow": "#00cc66",
        "scrollbar_arrow_active": "#00ff88", "scrollbar_arrow_hover": "#00dd77"
    },
    "Классический терминал": {
        "bg": "#0c0c0c", "fg": "#e0e0e0",
        "menu_bg": "#1a1a1a", "menu_fg": "#33ff33", "menu_active_bg": "#1e1e1e",
        "menu_active_fg": "#33ff33", "menu_highlight": "#33ff33",
        "left_header_bg": "#0c0c0c", "left_header_fg": "#33ff33",
        "tree_bg": "#0f0f0f", "tree_fg": "#33ff33", "tree_sel_bg": "#003300",
        "tree_heading_bg": "#0c0c0c", "tree_heading_fg": "#33ff33",
        "tree_frame_highlight": "#33ff33",
        "btn_default_bg": "#333333", "btn_default_fg": "#33ff33",
        "btn_danger_bg": "#4a2222", "btn_danger_fg": "#ff6666",
        "btn_accent_bg": "#1a4a1a", "btn_accent_fg": "#33ff33",
        "hotbar_bg": "#1a1a1a", "hotbar_fg": "#33ff33", "hotbar_highlight": "#33ff33",
        "hotbar_btn_bg": "#333333", "hotbar_btn_fg": "#33ff33",
        "console_bg": "#000000", "console_fg": "#33ff33",
        "scrollbar_thumb": "#2a5a2a", "scrollbar_thumb_active": "#3a7a3a",
        "scrollbar_thumb_hover": "#326a32", "scrollbar_trough": "#0f0f0f",
        "scrollbar_border": "#1e3a1e", "scrollbar_arrow": "#6fbf6f",
        "scrollbar_arrow_active": "#8fdf8f", "scrollbar_arrow_hover": "#7fcf7f",
        "console_highlight": "#33ff33",
        "scrollbar_bg": "#1a1a1a", "scrollbar_trough": "#0f0f0f",
        "scrollbar_arrow": "#33ff33", "scrollbar_active_bg": "#006600",
        "progress_trough": "#1a1a1a", "progress_light": "#33ff33", "progress_dark": "#006600",
        "select_bg": "#003300", "select_fg": "white"
    },
    "Синий неон": {
        "bg": "#0a0a1a", "fg": "#c0e0ff",
        "menu_bg": "#111122", "menu_fg": "#66aaff", "menu_active_bg": "#223344",
        "menu_active_fg": "#88ccff", "menu_highlight": "#4488cc",
        "left_header_bg": "#111122", "left_header_fg": "#aaccff",
        "tree_bg": "#0f0f1f", "tree_fg": "#b0d0ff", "tree_sel_bg": "#1e3a5f",
        "tree_heading_bg": "#111122", "tree_heading_fg": "#66aaff",
        "tree_frame_highlight": "#4488cc",
        "btn_default_bg": "#2a3a4a", "btn_default_fg": "#aaccff",
        "btn_danger_bg": "#4a2a2a", "btn_danger_fg": "#ff8888",
        "btn_accent_bg": "#1e3a5f", "btn_accent_fg": "#66aaff",
        "hotbar_bg": "#0f0f1a", "hotbar_fg": "#66aaff", "hotbar_highlight": "#4488cc",
        "hotbar_btn_bg": "#1a2a3a", "hotbar_btn_fg": "#88ccff",
        "console_bg": "#000000", "console_fg": "#66aaff", "console_highlight": "#4488cc",
        "scrollbar_thumb": "#2a4a6a", "scrollbar_thumb_active": "#4a7aaa",
        "scrollbar_thumb_hover": "#3a5f8a", "scrollbar_trough": "#0a0a12",
        "scrollbar_border": "#1a3a5a", "scrollbar_arrow": "#6f9fcf",
        "scrollbar_arrow_active": "#9fcfff", "scrollbar_arrow_hover": "#8fbfdf",
        "progress_trough": "#111122", "progress_light": "#66aaff", "progress_dark": "#336699",
        "select_bg": "#1e3a5f", "select_fg": "#ffffff"
    },
    "Фиолетовый киберпанк": {
        "bg": "#120a1e", "fg": "#e0c0ff",
        "menu_bg": "#160f24", "menu_fg": "#bb88ff", "menu_active_bg": "#2a1a3a",
        "menu_active_fg": "#d0a0ff", "menu_highlight": "#8844cc",
        "left_header_bg": "#160f24", "left_header_fg": "#d0b0ff",
        "tree_bg": "#1a1028", "tree_fg": "#c8a8ff", "tree_sel_bg": "#3a1e5a",
        "tree_heading_bg": "#160f24", "tree_heading_fg": "#bb88ff",
        "tree_frame_highlight": "#8844cc",
        "btn_default_bg": "#2a1a3a", "btn_default_fg": "#d0b0ff",
        "btn_danger_bg": "#4a1e2a", "btn_danger_fg": "#ff88aa",
        "btn_accent_bg": "#3a1e5a", "btn_accent_fg": "#bb88ff",
        "hotbar_bg": "#0f0a18", "hotbar_fg": "#bb88ff", "hotbar_highlight": "#8844cc",
        "hotbar_btn_bg": "#1e1430", "hotbar_btn_fg": "#d0a0ff",
        "console_bg": "#000000", "console_fg": "#bb88ff", "console_highlight": "#8844cc",
        "scrollbar_thumb": "#4a2a6a", "scrollbar_thumb_active": "#6a3a8a",
        "scrollbar_thumb_hover": "#5a327a", "scrollbar_trough": "#0f0a14",
        "scrollbar_border": "#2a1a3a", "scrollbar_arrow": "#9f6fcf",
        "scrollbar_arrow_active": "#c09fdf", "scrollbar_arrow_hover": "#b08fcf",
        "progress_trough": "#160f24", "progress_light": "#bb88ff", "progress_dark": "#6644aa",
        "select_bg": "#3a1e5a", "select_fg": "#ffffff"
    },
    "Красная тревога": {
        "bg": "#1a0a0a", "fg": "#ffd0d0",
        "menu_bg": "#1a0f0f", "menu_fg": "#ff6666", "menu_active_bg": "#3a2222",
        "menu_active_fg": "#ff8888", "menu_highlight": "#cc4444",
        "left_header_bg": "#1a0f0f", "left_header_fg": "#ffaaaa",
        "tree_bg": "#1f0f0f", "tree_fg": "#ffb0b0", "tree_sel_bg": "#4a1e1e",
        "tree_heading_bg": "#1a0f0f", "tree_heading_fg": "#ff6666",
        "tree_frame_highlight": "#cc4444",
        "btn_default_bg": "#3a2a2a", "btn_default_fg": "#ffaaaa",
        "btn_danger_bg": "#4a1e1e", "btn_danger_fg": "#ff6666",
        "btn_accent_bg": "#4a1a1a", "btn_accent_fg": "#ff8888",
        "hotbar_bg": "#0f0a0a", "hotbar_fg": "#ff6666", "hotbar_highlight": "#cc4444",
        "hotbar_btn_bg": "#2a1a1a", "hotbar_btn_fg": "#ff8888",
        "console_bg": "#000000", "console_fg": "#ff6666", "console_highlight": "#cc4444",
        "scrollbar_thumb": "#5a2a2a", "scrollbar_thumb_active": "#7a3a3a",
        "scrollbar_thumb_hover": "#6a3232", "scrollbar_trough": "#0f0a0a",
        "scrollbar_border": "#3a1a1a", "scrollbar_arrow": "#cf6f6f",
        "scrollbar_arrow_active": "#df9f9f", "scrollbar_arrow_hover": "#cf8f8f",
        "progress_trough": "#1a0f0f", "progress_light": "#ff6666", "progress_dark": "#993333",
        "select_bg": "#4a1e1e", "select_fg": "#ffffff"
    }
}

BUSY_STATUSES = {
    "Клонирование...", "Сборка...", "Удаление...", "Переустановка...",
    "Очистка кэша...", "Остановка...", "Авто-пересборка...", "Отмена...",
    "Обновление...", "Загрузка готовой сборки...", "Загрузка SDK...", "Установка Python...", "Установка Git...", "Установка .NET SDK..."
}

BUTTON_SEMANTICS = {
    "btn_install": "accent",
    "btn_run": "accent",
    "btn_open_folder": "default",
    "btn_open_upload": "default",
    "btn_reinstall": "danger",
    "btn_delete": "danger",
    "btn_clean_rebuild": "accent",
    "btn_show_system_logs": "default",
}

STATUS_ICONS = {
    "Клонирование...": "🔄 Клонирование...",
    "Сборка...": "⚙ Сборка...",
    "Удаление...": "🗑 Удаление...",
    "Переустановка...": "♻ Переустановка...",
    "Очистка кэша...": "🧹 Очистка кэша...",
    "Остановка...": "⏳ Остановка...",
    "Авто-пересборка...": "🔁 Авто-пересборка...",
    "Отмена...": "🛑 Отмена...",
    "Обновление...": "🔄 Обновление...",
    "Загрузка готовой сборки...": "📦 Готовая сборка...",
    "Установка Python...": "🐍 Установка Python...",
    "Установка Git...": "🌿 Установка Git...",
    "Установка .NET SDK...": "💠 Установка .NET SDK...",
    "Загрузка SDK...": "⬇ Загрузка SDK...",
    "Ошибка": "❌ Ошибка",
    "installed": "☑ Установлено",
    "partial_build": "⚠ Сборка не завершена",
    "clone_incomplete": "⚠ Клон не завершён",
    "missing": "☐ Не установлено",
    "unknown": "❓ Требуется проверка",
}